# Main menu navigation
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  # 标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  # 清单||fas fa-list:
  #   音乐: /music/ || fas fa-music
  #   照片: /Gallery/ || fas fa-images
  #   电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于我: /about/ || fas fa-heart

# Navigation bar
nav:
  display_title: true
  display_post_title: true
  fixed: false

# Code blocks
code_blocks:
  theme: light
  macStyle: true
  height_limit: false
  word_wrap: true
  copy: true
  language: true
  shrink: false
  fullpage: false

# Copy settings
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# Social links
social:
  fab fa-github: https://github.com/starbovo || Github
  fas fa-envelope: mailto:1598718223@qq.com || Email
  fab fa-mastodon: https://tea.codes/@ultstar || Mastodon

# Search
search:
  use:
  placeholder:
  algolia_search:
    hitsPerPage: 6
  local_search:
    preload: false
    top_n_per_article: 1
    unescape: false

# Math
math:
  use: katex
  per_page: true
  hide_scrollbar: true
  mathjax:
    enableMenu: true
    tags: none
  katex:
    copy_tex: false

# Images
favicon: https://z3.ax1x.com/2021/08/16/fRWc11.png

avatar:
  img: https://s1.ax1x.com/2022/06/19/Xjcb28.jpg
  effect: false

disable_top_img: false
index_img: https://pica.zhimg.com/v2-45c7626bb36d74522e7cf22ec27bce66_r.jpg
default_top_img:
archive_img: https://pic1.zhimg.com/v2-7341158a7843d3047fb06d426d550c90_r.jpg
tag_img: https://pic1.zhimg.com/v2-d8fd9dbc1b61678c06201603eab67e20_r.jpg
tag_per_img:
category_img: https://pic3.zhimg.com/v2-6916d86881fd01cfe853501028a2227a_r.jpg
category_per_img:
footer_img: false

background: url(https://pic2.zhimg.com/80/v2-0a67637e2c24c31e307d0995cdf94350_720w.jpg)

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:

error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

error_404:
  enable: true
  subtitle: '找不着地儿了！您出门左转试试'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: false
    label: true
  post:
    position: left
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

# Index page
index_site_info_top:
index_top_img_height:
index_layout: 3

subtitle:
  enable: true
  effect: true
  typed_option:
  source: false
  sub:
    - 为自由争朝夕
    - 扛起整座山谷到我的梦里
    - 东边不亮西边亮
    - 别把我遗忘在上一个世纪
    - 我最爱去的唱片店
    - 大家好我们是A-SOUL！

# Post content
index_post_content:
  method: 2
  length: 500

# Table of Contents
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: false
  text:
  QR_code:

post_edit:
  enable: false
  url:

related_post:
  enable: true
  limit: 6
  date_type: created

post_pagination: 1

noticeOutdate:
  enable: true
  style: flat
  limit_day: 500
  position: top
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# Footer
footer:
  owner:
    enable: true
    since: 2021
  copyright:
    enable: true
    version: true
  custom_text: welcome!

# Aside
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-qq
      text: 加俺好友
      link: https://qm.qq.com/cgi-bin/qm/qr?k=nItm-FTykd_c0e7DgC47eBsmJUUk9ONG&noverify=0
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order:
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1
    sort_order:
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    runtime_date: 8/2/2021 00:00:00
  card_newest_comments:
    enable: false
    sort_order:
    limit: 6
    storage: 10
    avatar: true

# Share system
share:
  use: sharejs
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq
  addtoany:
    item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# Comments
comments:
  use: Valine
  text: true
  lazyload: true
  count: true
  card_post_count: true

disqus:
  shortname:
  apikey:

disqusjs:
  shortname:
  apikey:
  option:

livere:
  uid:

gitalk:
  client_id:
  client_secret:
  repo:
  owner:
  admin:
  option:

valine:
  appId: aszU4uiVyVhcnLnrmcPm3hEN-gzGzoHsz
  appKey: N9akIc8L6AiC3mQETEyFxCaD
  avatar: monsterid
  serverURLs:
  bg: /img/comment_bg.png
  visitor: false
  option:
    pageSize: 10
    lang: zh-CN
    placeholder: 记得留下你的昵称和邮箱，可以快速收到回复
    guest_info: nick,mail,link
    recordIP: false
    emojiCDN: '//i0.hdslb.com/bfs/emote/'
    enableQQ: true
    requiredFields: nick,mail

waline:
  serverURL:
  pageview: false
  option:

utterances:
  repo:
  issue_term: pathname
  light_theme: github-light
  dark_theme: photon-dark

facebook_comments:
  app_id:
  user_id:
  pageSize: 10
  order_by: social
  lang: en_US

twikoo:
  envId:
  region:
  visitor: false
  option:

giscus:
  repo:
  repo_id:
  category_id:
  light_theme: light
  dark_theme: dark

remark42:
  host:
  siteId:

artalk:
  server:
  site:
  visitor: false

# Chat
chat:
  use:
  rightside_button: false
  button_hide_show: false

chatra:
  id:

tidio:
  public_key:

crisp:
  website_id:

# Word count
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# Busuanzi
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# Translation
translate:
  enable: true
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: '繁'
  msgToSimplifiedChinese: '簡'

# Read & Dark mode
readmode: true
darkmode:
  enable: true
  button: true
  autoChangeMode: 1

# Lightbox
lightbox: fancybox

# Rightside button
rightside_bottom:
rightside_scroll_percent: false
rightside_item_order:
  enable: false
  hide:
  show:
rightside_config_animation: true

# Anchor
anchor:
  auto_update: false
  click_to_scroll: false

# Display mode
display_mode: light

# Beautify
beautify:
  enable: true
  field: site
  title_prefix_icon: '\f0c1'
  title_prefix_icon_color: '#F47466'

# Font
font:
  global_font_size:
  code_font_size:
  font_family:
  code_font_family:

blog_title_font:
  font_link:
  font_family:

# Divider icon
hr_icon:
  enable: true
  icon: '\f197'
  icon_top: -10px

# Activate power mode
activate_power_mode:
  enable: true
  colorful: true
  shake: false
  mobile: false

# Background effects
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

canvas_fluttering_ribbon:
  enable: false
  mobile: false

canvas_nest:
  enable: false
  color: '0,0,255'
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false

fireworks:
  enable: true
  zIndex: 9999
  mobile: true

click_heart:
  enable: false
  mobile: false

clickShowText:
  enable: false
  text:
  fontSize: 15px
  random: false
  mobile: false

# Preloader
preloader:
  enable: false
  source: 1
  pace_css_url:

# Enter transitions
enter_transitions: true

# Category/Tag UI
category_ui:
tag_ui:

# Mask
mask:
  header: true
  footer: true

# Mermaid
mermaid:
  enable: false
  code_write: false
  theme:
    light: default
    dark: dark

# Note
note:
  style: simple
  icons: true
  border_radius: 3
  light_bg_offset: 0

# Pjax
pjax:
  enable: false
  exclude:

# Aplayer
aplayerInject:
  enable: false
  per_page: true

# Snackbar
snackbar:
  enable: false
  position: bottom-left
  bg_light: '#49b1f5'
  bg_dark: '#121212'

# Instant page
instantpage: false

# Pangu
pangu:
  enable: false
  field: site

# Lazyload
lazyload:
  enable: false
  native: false
  field: site
  placeholder:
  blur: false

# PWA
pwa:
  enable: false
  manifest:
  apple_touch_icon:
  favicon_32_32:
  favicon_16_16:
  mask_icon:

# Open Graph
Open_Graph_meta:
  enable: true
  option:

# CSS prefix
css_prefix: true

# Inject
inject:
  head:
  bottom:

# CDN
CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: true

# Analysis
baidu_analytics:
google_analytics:
cloudflare_analytics:
microsoft_clarity:
umami_analytics:
  enable: false
  serverURL:
  website_id:
  option:
  UV_PV:
    site_uv: false
    site_pv: false
    page_pv: false
    token:

google_tag_manager:
  tag_id:

# Ad
google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

ad:
  index:
  aside:
  post:

# Verification
site_verification:

# Injection for third-party plugins
# hexo-butterfly-swiper
swiper:
  enable: false
  priority: 5
  enable_page: all
  timemode: date
  layout:
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  custom_css: https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/css/swiper.min.css
  custom_js: https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/js/swiper.min.js

# hexo-butterfly-artitalk-pro
artitalk:
  enable:
    card: false
    page: true
  priority: 5
  enable_page: all
  layout:
    type: class
    name: sticky_layout
    index: 0
  path: artitalk
  front_matter:
    title: 碎碎念
  appId: aszU4uiVyVhcnLnrmcPm3hEN-gzGzoHsz
  appKey: N9akIc8L6AiC3mQETEyFxCaD
  exclude:
    - /artitalk/
    - /posts/
  js: https://cdn.jsdelivr.net/npm/artitalk
  option:
    serverURL: https://aszu4uiv.lc-cn-n1-shared.com
    lang: zh
    pageSize: 1
    color1: '#49b1f5'
    color2: '#00c4b6'
    atEmoji:
      Mafumafu1: https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Mafumafu/199749454.png
      Mafumafu2: https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Mafumafu/199749455.png

# hexo-butterfly-clock
electric_clock:
  enable: true
  priority: 5
  enable_page: all
  exclude:
  layout:
    type: class
    name: sticky_layout
    index: 0
  loading: /img/loading.gif
